-- ROUND
SELECT ROUND(RAND() * 10);

-- WORK WITH DATE
ALTER TABLE MINIONS
ADD DATA_FILED DATETIME;

UPDATE MINIONS
	SET DATA_FILED = '2020-12-01';
    
SELECT
	NAME, CAST(DATA_FILED AS DATE)
FROM
	minions;

-- EXTRACT DAY OR YEAR DROM DATATIMEFIELD
SELECT EXTRACT(DAY FROM DATA_FILED) AS MY_DAY FROM MINIONS;
SELECT YEAR(DATA_FILED) AS MY_YEAR FROM MINIONS;

SELECT TIMESTAMPDIFF(DAY, DATA_FILED, NOW()) AS DAY_TO_NOW FROM MINIONS;

-- DATAFORMAT
SELECT DATE_FORMAT(DATA_FILED, "%D %M") AS MY_DATE FROM MINIONS;

SELECT
	*
FROM MINIONS
WHERE
	DAY(DATA_FILED) BETWEEN 2 AND 5
ORDER BY NAME DESC;

-- WILDCART
SELECT * FROM MINIONS
WHERE NAME NOT LIKE '%EO%';

